-- MySQL Script generated by MySQL Workbench
-- Sat Apr 28 22:04:02 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema chr_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chr_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chr_db` DEFAULT CHARACTER SET utf8 ;
USE `chr_db` ;

-- -----------------------------------------------------
-- Table `chr_db`.`chromosome`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chr_db`.`chromosome` ;

CREATE TABLE IF NOT EXISTS `chr_db`.`chromosome` (
  `name` VARCHAR(20) NOT NULL,
  `source` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chr_db`.`locus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chr_db`.`locus` ;

CREATE TABLE IF NOT EXISTS `chr_db`.`locus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `whole_seq` MEDIUMTEXT NOT NULL,
  `chr_location` VARCHAR(50) NOT NULL,
  `locus_name` VARCHAR(20) NOT NULL,
  `chr_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `chr_name_fk`
    FOREIGN KEY (`chr_name`)
    REFERENCES `chr_db`.`chromosome` (`name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `chr_db`.`locus` (`id` ASC);

CREATE INDEX `chr_name_fk_idx` ON `chr_db`.`locus` (`chr_name` ASC);

CREATE INDEX `chr_location_idx` ON `chr_db`.`locus` (`chr_location` ASC);


-- -----------------------------------------------------
-- Table `chr_db`.`accession`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chr_db`.`accession` ;

CREATE TABLE IF NOT EXISTS `chr_db`.`accession` (
  `accession_id` INT NOT NULL AUTO_INCREMENT,
  `accession_num` VARCHAR(20) NOT NULL,
  `locus_id` INT NOT NULL,
  `latest_version` ENUM('T', 'F') NOT NULL,
  PRIMARY KEY (`accession_id`),
  CONSTRAINT `locus_id_fk`
    FOREIGN KEY (`locus_id`)
    REFERENCES `chr_db`.`locus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `locus_id_fk_idx` ON `chr_db`.`accession` (`locus_id` ASC);

CREATE UNIQUE INDEX `id_UNIQUE` ON `chr_db`.`accession` (`accession_id` ASC);


-- -----------------------------------------------------
-- Table `chr_db`.`cds`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chr_db`.`cds` ;

CREATE TABLE IF NOT EXISTS `chr_db`.`cds` (
  `cds_id` INT NOT NULL AUTO_INCREMENT,
  `gene_name` VARCHAR(100) NULL,
  `product_name` VARCHAR(500) NULL,
  `product_id` VARCHAR(100) NULL,
  `seq_location` MEDIUMTEXT NULL,
  `whole_seq` MEDIUMTEXT NULL,
  `translation` MEDIUMTEXT NULL,
  `complement` ENUM('T', 'F') NULL,
  `locus_id` INT NOT NULL,
  PRIMARY KEY (`cds_id`),
  CONSTRAINT `locus_fk`
    FOREIGN KEY (`locus_id`)
    REFERENCES `chr_db`.`locus` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `locus_fk_idx` ON `chr_db`.`cds` (`locus_id` ASC);

CREATE INDEX `gene_name_idx` ON `chr_db`.`cds` (`gene_name` ASC);

CREATE INDEX `product_name_idx` ON `chr_db`.`cds` (`product_name` ASC);


-- -----------------------------------------------------
-- Table `chr_db`.`restriction_enzyme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chr_db`.`restriction_enzyme` ;

CREATE TABLE IF NOT EXISTS `chr_db`.`restriction_enzyme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `recogn_seq` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `re_id_UNIQUE` ON `chr_db`.`restriction_enzyme` (`id` ASC);


-- -----------------------------------------------------
-- Table `chr_db`.`restriction_sites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chr_db`.`restriction_sites` ;

CREATE TABLE IF NOT EXISTS `chr_db`.`restriction_sites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `locus_id` INT NOT NULL,
  `re_id` INT NOT NULL,
  `start_position` INT NOT NULL,
  `end_position` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `locus_id_foreign_k`
    FOREIGN KEY (`locus_id`)
    REFERENCES `chr_db`.`locus` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `re_id_foreign_k`
    FOREIGN KEY (`re_id`)
    REFERENCES `chr_db`.`restriction_enzyme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `re_id_fk_idx` ON `chr_db`.`restriction_sites` (`re_id` ASC);

CREATE UNIQUE INDEX `id_UNIQUE` ON `chr_db`.`restriction_sites` (`id` ASC);


-- -----------------------------------------------------
-- Table `chr_db`.`codon_usage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chr_db`.`codon_usage` ;

CREATE TABLE IF NOT EXISTS `chr_db`.`codon_usage` (
  `codon` CHAR(3) NOT NULL,
  `frequency_100` FLOAT NOT NULL,
  `ratio_aa` FLOAT NOT NULL,
  `amino_acid` VARCHAR(3) NOT NULL,
  `chr_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`codon`),
  CONSTRAINT `chr_name_foreign_k`
    FOREIGN KEY (`chr_name`)
    REFERENCES `chr_db`.`chromosome` (`name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `codon_UNIQUE` ON `chr_db`.`codon_usage` (`codon` ASC);

CREATE INDEX `chr_name_fk_idx` ON `chr_db`.`codon_usage` (`chr_name` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
